"""modified game model

Revision ID: 51679f8c5ae0
Revises: d9d61ad87604
Create Date: 2023-09-25 18:05:46.749484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51679f8c5ae0'
down_revision = 'd9d61ad87604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
