"""modified game model

Revision ID: d9d61ad87604
Revises: 0b366969bbcf
Create Date: 2023-09-25 18:01:01.943996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d61ad87604'
down_revision = '0b366969bbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.drop_column('developer')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('developer', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
