"""added cascade parameter

Revision ID: dac41ebebe0e
Revises: 77dc71f1c42d
Create Date: 2023-10-01 02:20:22.518250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac41ebebe0e'
down_revision = '77dc71f1c42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_library', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_library_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_game_library_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_library', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_library_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_game_library_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
